##
## EPITECH PROJECT, 2024
## Makefile
## File description:
## jitter jitter
##

# Silence the outputs we wish not to listen to
SILENT	=	@

# Colour codes
C_BACKGROUND	=	\033[48;5;16m
C_RED	=	\033[38;5;9m$(C_BACKGROUND)
C_PINK	=	\033[38;5;206m$(C_BACKGROUND)
C_CYAN	=	\033[38;5;87m$(C_BACKGROUND)
C_BLUE	=	\033[38;5;45m$(C_BACKGROUND)
C_WHITE	=	\033[38;5;15m$(C_BACKGROUND)
C_GREEN	=	\033[38;5;46m$(C_BACKGROUND)
C_RESET	=	\033[0m$(C_BACKGROUND)
C_YELLOW	=	\033[38;5;226m$(C_BACKGROUND)

# Compile the project
all:
#	$(SILENT) make SILENT=$(SILENT) -C ./my_lib
	$(SILENT) exit 0

clean:
#	$(SILENT) make SILENT=$(SILENT) -C ./my_lib clean
	$(SILENT) exit 0

fclean: clean
#	$(SILENT) make SILENT=$(SILENT) -C ./my_lib fclean
	$(SILENT) exit 0

tests_run:
#	$(SILENT) make SILENT=$(SILENT) -C ./my_lib tests_run
	$(SILENT) exit 0

coverage:
#	$(SILENT) make SILENT=$(SILENT) -C ./my_lib coverage
	$(SILENT) exit 0

debug: 
#	$(SILENT) make SILENT=$(SILENT) -C ./my_lib debug
	$(SILENT) exit 0

re: fclean all

.PHONY: fclean all clean re tests_run coverage debug

