name: workflow_runner
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
    WORKFLOW_RUNNER: "github"
    BINARY_NAME: "runner"

jobs:
  check-runner-health:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile code
        id: compilation-status
        run: |
          make fclean
          make

      - name: Check unit test
        id: unit-test-status
        run: |
          make tests_run

  publish-package:
    needs: check-runner-health
    runs-on: ubuntu-latest
    if: ${{ needs.check-runner-health.result == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build package
        run: |
          make fclean
          make
      
      - name: Update author
        run: |
          git config --local user.name "${{secrets.USER_NAME_E}}"
          git config --local user.email "${{secrets.USER_EMAIL_E}}"
          
      - name: Publish binary as GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${BINARY_NAME}
          # tag_name: ${{ github.ref }}
          # release_name: ${{ github.ref }}
          # body: |
          #   Release ${{ github.ref }}
          # draft: false
          # prerelease: false


